Fix config (config on bedrock.start now).
digitalbazaar/bedrock-vc-issuer pull request #68
Opened 2021-09-08 23:56 UTC by dmitrizagidulin

Adding support for did:key and did:v1 DIDs, fix config eventing.

2021-09-09 17:47 UTC, dlongley requested changes

2021-09-09 17:47 UTC, dlongley commented on lib/config.js
> +config['did-io'].methods.key.verificationSuite = Ed25519VerificationKey2020;
bedrock-did-io needs to be required if it will be modified here.

2021-09-09 17:47 UTC, dlongley commented on lib/config.js
> +config['https-agent'].rejectUnauthorized = false;
I think we have a different pattern/practice for setting this -- we don't typically set it in default configs in modules. Can this be checked?

2021-09-09 17:47 UTC, dlongley commented on lib/config.js
> +config['did-io'].methods.v1.cryptoLd = cryptoLd;
I suspect we want to set all of these things at the app level, not here. This creates a tight binding and introduces other dependencies that make this module harder to maintain.

2021-09-23 21:05 UTC, dmitrizagidulin commented
Closing the PR, moving this config to the top level app.

2021-09-23 21:05 UTC, closed without merging